In [1]:
import numpy as np
import pandas as pd
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [2]:
df=pd.read_csv('Language Detection.csv')

In [3]:
df.sample(5)

,Text,Language
3228,oh bobo ele é rico e bonito o que mais eu pode...,Portugeese
5276,Ahora hay algo un poco emocionante y reservado...,Spanish
6139,Модели редактирования Википедии свойственна во...,Russian
2502,வண்டியில் வீட்டில் நர்சிஸ் அவள் வீட்டிற்கு வந்...,Tamil
231,For this reason the most fundamental science i...,English


In [4]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text, flags=re.UNICODE)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [5]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(df["Text"])

In [6]:
word_index = tokenizer.word_index

In [7]:
word_index

{'<OOV>': 1,
 'de': 2,
 'a': 3,
 'the': 4,
 'en': 5,
 'la': 6,
 'que': 7,
 'in': 8,
 'of': 9,
 'wikipedia': 10,
 'and': 11,
 'du': 12,
 'e': 13,
 'to': 14,
 'un': 15,
 'di': 16,
 'i': 17,
 'le': 18,
 'o': 19,
 'et': 20,
 'के': 21,
 'is': 22,
 'se': 23,
 'je': 24,
 'à': 25,
 'att': 26,
 'da': 27,
 'wikipédia': 28,
 'det': 29,
 'y': 30,
 'por': 31,
 'des': 32,
 'में': 33,
 'that': 34,
 'les': 35,
 'el': 36,
 'och': 37,
 'в': 38,
 'no': 39,
 'for': 40,
 'as': 41,
 'है': 42,
 'para': 43,
 'una': 44,
 'che': 45,
 'som': 46,
 'you': 47,
 'vous': 48,
 'il': 49,
 'और': 50,
 'em': 51,
 'at': 52,
 'kan': 53,
 'في': 54,
 'и': 55,
 'er': 56,
 'es': 57,
 'να': 58,
 'är': 59,
 'het': 60,
 'på': 61,
 'um': 62,
 'एक': 63,
 'was': 64,
 'est': 65,
 'من': 66,
 'om': 67,
 'on': 68,
 'como': 69,
 'você': 70,
 'è': 71,
 'को': 72,
 'ou': 73,
 'une': 74,
 'dans': 75,
 'har': 76,
 'कि': 77,
 'een': 78,
 '\u200b': 79,
 'sie': 80,
 'non': 81,
 'si': 82,
 'से': 83,
 'nature': 84,
 'हैं': 85,
 'los': 86,
 'par': 8

In [8]:
sequences = tokenizer.texts_to_sequences(df["Text"])

In [9]:
sequences

[[84, 8, 4, 11212, 4937, 22, 4, 704, 2717, 1388, 960, 115, 2718],
 [84, 152, 8008, 14, 4, 11213, 9, 4, 2717, 960, 11, 236, 14, 324, 8, 731],
 [4, 788, 9, 84, 22, 3, 1189, 255, 202, 4, 516, 468, 9, 604],
 [1304,
  2719,
  92,
  468,
  9,
  84,
  548,
  8009,
  22,
  732,
  4938,
  41,
  3,
  4137,
  4138,
  150,
  273,
  704,
  11213],
 [184,
  4,
  414,
  84,
  22,
  11214,
  150,
  4,
  8010,
  6076,
  84,
  11,
  22,
  11215,
  150,
  4,
  2720,
  414,
  2204,
  115,
  8011,
  18321,
  18322,
  11216,
  11,
  8,
  11217,
  1001,
  11218,
  18323,
  18324],
 [240,
  8,
  11217,
  4139,
  2204,
  22,
  3511,
  415,
  41,
  4,
  2720,
  6077,
  9,
  4,
  18325,
  414,
  18326,
  11219,
  188,
  3512,
  915,
  14,
  4,
  18327,
  8012,
  34,
  1991,
  1698,
  11,
  273,
  1190,
  9,
  4,
  960,
  4939,
  9,
  373,
  2443,
  11220],
 [252,
  329,
  4,
  1827,
  9,
  84,
  41,
  3,
  4140,
  4,
  2717,
  2718,
  22,
  294,
  9,
  818,
  18328,
  9,
  4,
  1305,
  1699,
  184,
  118,
  3513

In [10]:
max_length = 20

padded_sequences = pad_sequences(
    sequences,
    maxlen=max_length,
    padding='post'
)

In [11]:
padded_sequences

array([[   84,     8,     4, ...,     0,     0,     0],
       [   84,   152,  8008, ...,     0,     0,     0],
       [    4,   788,     9, ...,     0,     0,     0],
       ...,
       [ 1600,   186, 48697, ...,     0,     0,     0],
       [ 1188,  1824,  4124, ...,     0,     0,     0],
       [ 4136,    91,  1187, ..., 48707,     0,     0]], dtype=int32)

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
lb=LabelEncoder()
labels = lb.fit_transform(df["Language"])

In [14]:
labels

array([3, 3, 3, ..., 9, 9, 9])

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    padded_sequences,
    labels,
    test_size=0.2
)

In [16]:
X_train

array([[  587,     4,  6106, ...,     0,     0,     0],
       [ 1513,  8624,  6482, ...,     0,     0,     0],
       [ 3357,   213,     0, ...,     0,     0,     0],
       ...,
       [  179,  2170,  5882, ...,     0,     0,     0],
       [46236, 46237,  7807, ...,     0,     0,     0],
       [  759, 43271,    95, ..., 43276,    17, 43277]], dtype=int32)

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [18]:
vocab_size=len(word_index)+1
embedding_dim = 64
max_length = 20
num_classes = len(lb.classes_)

In [19]:
model=Sequential()

In [20]:
model.add(Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim,
    input_length=max_length
))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.add(LSTM(units=64))

In [22]:
model.add(Dense(num_classes,activation='softmax'))

In [23]:
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [24]:
model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test)
)

Epoch 1/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.2496 - loss: 2.3380 - val_accuracy: 0.6867 - val_loss: 0.9942
Epoch 2/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 20s 46ms/step - accuracy: 0.7833 - loss: 0.7233 - val_accuracy: 0.8854 - val_loss: 0.4330
Epoch 3/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 21s 47ms/step - accuracy: 0.9247 - loss: 0.2650 - val_accuracy: 0.9018 - val_loss: 0.3458
Epoch 4/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9594 - loss: 0.1599 - val_accuracy: 0.9226 - val_loss: 0.2948
Epoch 5/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9799 - loss: 0.0867 - val_accuracy: 0.9217 - val_loss: 0.3418
Epoch 6/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9775 - loss: 0.0866 - val_accuracy: 0.9120 - val_loss: 0.3389
Epoch 7/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 22s 46ms/step - accuracy: 0.9898 - loss: 0.0424 - val_accuracy: 0.9279 - val_loss: 0.3251
Epoch 8/10
259/259 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9924 - loss: 0.0382 - 

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 64)         │     3,117,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 17)             │         1,105 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,380,021 (35.78 MB)

 Trainable params: 3,126,673 (11.93 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6,253,348 (23.85 MB)

In [ ]:
new_text = "scusa se ti interrompo"# ================================
# LANGUAGE PREDICTION TEST BLOCK
# ================================

import numpy as np
import re
from tensorflow.keras.preprocessing.sequence import pad_sequences


# 1. Cleaning function (same as training)
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text, flags=re.UNICODE)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


# 2. Prediction function
def predict_language(text):

    # Step 1: Clean text
    cleaned = clean_text(text)

    # Step 2: Convert to sequence
    sequence = tokenizer.texts_to_sequences([cleaned])

    # Step 3: Padding
    padded = pad_sequences(
        sequence,
        maxlen=max_length,
        padding='post'
    )

    # Step 4: Predict probabilities
    prediction = model.predict(padded, verbose=0)

    # Step 5: Get predicted index
    predicted_index = np.argmax(prediction, axis=1)[0]

    # Step 6: Convert index to language
    predicted_language = lb.inverse_transform([predicted_index])[0]

    # Step 7: Get confidence
    confidence = prediction[0][predicted_index]

    return predicted_language, confidence


# ================================
# TEST EXAMPLES
# ================================

test_sentences = [
    "scusa se ti interrompo",
    "jeg er nødt til at komme i gang",
    "ödevlerle boğuşuyorum",
    "dus vandaag gaan we leren",
    "a página discussão associada"
]

for sentence in test_sentences:
    language, confidence = predict_language(sentence)
    print(f"Text: {sentence}")
    print(f"Predicted Language: {language}")
    print(f"Confidence: {confidence:.4f}")
    print("-" * 50)


# ================================
# CUSTOM USER INPUT TEST
# ================================

user_input = input("Enter text to detect language: ")

language, confidence = predict_language(user_input)

print(f"\nPredicted Language: {language}")
print(f"Confidence: {confidence:.4f}")

Text: scusa se ti interrompo
Predicted Language: Italian
Confidence: 0.9927
--------------------------------------------------
Text: jeg er nødt til at komme i gang
Predicted Language: Danish
Confidence: 0.9840
--------------------------------------------------
Text: ödevlerle boğuşuyorum
Predicted Language: English
Confidence: 0.9072
--------------------------------------------------
Text: dus vandaag gaan we leren
Predicted Language: Dutch
Confidence: 0.7401
--------------------------------------------------
Text: a página discussão associada
Predicted Language: Portugeese
Confidence: 0.9957
--------------------------------------------------
Enter text to detect language: my name is dhruv

Predicted Language: English
Confidence: 0.9970
